# Generated by Powerlevel10k configuration wizard.
# Basic minimal configuration for p10k
# To customize further, run `p10k configure` or edit this file manually.

'builtin' 'local' '-a' 'p10k_config_opts'
[[ ! -o 'aliases'         ]] || p10k_config_opts+=('aliases')
[[ ! -o 'sh_glob'         ]] || p10k_config_opts+=('sh_glob')
[[ ! -o 'no_brace_expand' ]] || p10k_config_opts+=('no_brace_expand')
'builtin' 'setopt' 'no_aliases' 'no_sh_glob' 'brace_expand'

() {
  emulate -L zsh -o extended_glob

  # Unset all configuration options.
  unset -m '(POWERLEVEL9K_*|DEFAULT_USER)~POWERLEVEL9K_GITSTATUS_DIR'

  # Left prompt segments.
  typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
    dir                     # current directory
    vcs                     # git status
    prompt_char             # prompt symbol
  )

  # Right prompt segments.
  typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(
    status                  # exit code of the last command
    command_execution_time  # duration of the last command
    background_jobs         # presence of background jobs
    direnv                  # direnv status (https://direnv.net/)
    virtualenv              # python virtual environment (https://docs.python.org/3/library/venv.html)
    anaconda                # conda environment (https://conda.io/)
    time                    # current time
  )

  # Basic style settings
  typeset -g POWERLEVEL9K_PROMPT_ON_NEWLINE=true
  typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=''
  typeset -g POWERLEVEL9K_MULTILINE_NEWLINE_PROMPT_PREFIX=''
  typeset -g POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX=''
  typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_SUFFIX=''
  typeset -g POWERLEVEL9K_MULTILINE_NEWLINE_PROMPT_SUFFIX=''
  typeset -g POWERLEVEL9K_MULTILINE_LAST_PROMPT_SUFFIX=''
  
  # Set prompt character
  typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIINS_CONTENT_EXPANSION='❯'
  typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VICMD_CONTENT_EXPANSION='❮'
  typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIINS_FOREGROUND='green'
  typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_VIINS_FOREGROUND='red'
  typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VICMD_FOREGROUND='blue'

  # Basic git settings  
  typeset -g POWERLEVEL9K_VCS_CLEAN_FOREGROUND='green'
  typeset -g POWERLEVEL9K_VCS_MODIFIED_FOREGROUND='yellow'
  typeset -g POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND='cyan'
  
  # Directory settings
  typeset -g POWERLEVEL9K_DIR_FOREGROUND='blue'
  typeset -g POWERLEVEL9K_SHORTEN_STRATEGY='truncate_to_last'
  
  # Status settings
  typeset -g POWERLEVEL9K_STATUS_VERBOSE=false
  
  # Time settings
  typeset -g POWERLEVEL9K_TIME_FORMAT='%D{%H:%M:%S}'
  
  # Transient prompt (replaces old prompts with just the command char)
  typeset -g POWERLEVEL9K_TRANSIENT_PROMPT=off
  
  # Instant prompt mode (precmd hooks before showing prompt)
  typeset -g POWERLEVEL9K_INSTANT_PROMPT=verbose
  
  # Hot reload
  typeset -g POWERLEVEL9K_DISABLE_HOT_RELOAD=false
}

(( ${#p10k_config_opts} )) && setopt ${p10k_config_opts[@]}
'builtin' 'unset' 'p10k_config_opts'